### ISSUE TITLE
Result from script

### ISSUE THREAD

**Issue by eyalish** [YoavRamon/post-check#2]
Hello, 
how to fix this result:

`returncode: 1
stdout:

stderr:
Traceback (most recent call last):
  File "./post-check.py", line 1, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
`
Do you know if this code works on new IsraelPost API?
also, does it require ssh access or not

**Comment by YoavRamon** [comment]
Notice that you didn't install the requirements as I mentioned:
`pip install -r requirements.txt`
This does not work with IsraelPost API.

**Comment by eyalish** [comment]
> 
> 
> Notice that you didn't install the requirements as I mentioned:
> `pip install -r requirements.txt`
> This does not work with IsraelPost API.

Yoav, I couldn't run this without SSH access. and test it works
I'm looking for a solution
thanks!
